/* empty css                      */import{a as w,i as l,S as R}from"./assets/vendor-Qob_5Ba8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const y of s.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&n(y)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const L="46843956-48321f6890b82a65cca7319ef",P="https://pixabay.com/api/";async function f(r,t=1){const o=new URLSearchParams({key:L,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}),n=`${P}?${o}`;try{return(await w.get(n)).data}catch(e){throw iziToast.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"}),console.error("There was a problem with the fetch operation:",e),e}}const S=document.querySelector(".gallery");function h(r){const t=r.map(o=>`<li class="gallery-item">
	  <a class="gallery-link" href="${o.largeImageURL}">
		<img 
			class="gallery-image" 
			src="${o.webformatURL}" 
			alt="${o.tags}" 
			/>
        <div class="gallery-info">
        <p class="gallery-likes"><span>Likes:</span> ${o.likes}</p>
        <p class="gallery-views"><span>Views:</span> ${o.views}</p>
        <p class="gallery-comments"><span>Comments:</span> ${o.comments}</p>
        <p class="gallery-downloads"><span>Downloads:</span> ${o.downloads}</p>
      </div>    
	  </a>
    </li>
    `).join("");S.insertAdjacentHTML("beforeend",t)}let u,c="",i=1,d=0;const g=document.querySelector(".gallery"),b=document.querySelector(".form"),v=document.querySelector(".input"),p=document.querySelector(".loader"),m=document.querySelector(".loader-extra"),a=document.querySelector(".load-more");a.style.display="none";b.addEventListener("submit",E);a.addEventListener("click",q);async function E(r){if(r.preventDefault(),c=v.value.trim(),i=1,!c){l.error({title:"Error",message:"Please enter a search query...",position:"topRight"});return}p.style.display="block",a.style.display="none";try{const t=await f(c,i);if(d=t.totalHits,p.style.display="none",t.hits.length===0){g.innerHTML="",l.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:5e3}),b.reset();return}g.innerHTML="",h(t.hits),u=new R(".gallery a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionDelay:250});const o=Math.ceil(d/15);i>=o?(a.style.display="none",l.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:5e3})):a.style.display="block"}catch(t){p.style.display="none",l.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"}),console.error("Error fetching images:",t)}}async function q(){i+=1,m.style.display="block",a.style.display="none";try{const r=await f(c,i);if(m.style.display="none",r.hits.length===0){a.style.display="none",l.info({title:"No More Results",message:"No more images available.",position:"topRight",timeout:5e3});return}h(r.hits),$();const t=Math.ceil(d/15);i>=t?(a.style.display="none",l.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:5e3})):a.style.display="block",u&&u.refresh()}catch(r){p.style.display="none",a.style.display="block",l.error({title:"Error",message:"Failed to fetch more images. Please try again later.",position:"topRight"}),console.error("Error fetching more images:",r)}}function $(){const r=g.querySelector(".gallery-item:last-child");if(!r)return;const t=r.getBoundingClientRect().height;console.log(t),window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
